# Profile section
profile:
  first_name: Rodrigo
  last_name: Cabral
  picture: static/img/perfil.jpg # Local picture
  contact:
    address_one: São João de Meriti, Brasil
    address_two:
    phone: +55 21 99390-3683
  email: rodrigo.oliveiracabral@hotmail.com
  description: >
    I'm a bachelor's Computer Science, M.Sc. student at Military Institute of Engineering - IME/RJ, studying machine learning techniques, graduated in Computer Science at Centro Universitário Carioca - Unicarioca(2018). 
    I'm passionate about how technology can change the world, enthusiast about programming languages, process optimization, ETL and technologies in general. Trying to learn everything I can and apply it so I can help companies grow their business. If you have a project I can help with, please get in touch.

# Social section
social:
  github: https://github.com/RodrigoOBC
  linkedin: https://www.linkedin.com/in/rodrigo-cabral-sfpc-0280b3121/


# Experience section
experience:
  item0:
    position: Analista de Tesde de Software Jr.
    company: Radix Engenharia e Software
    from: Janeiro 2020
    to: Present
    description: >
    link: http://www.radixeng.com.br/
  item1:
    position: Estagiario de Tesde e Qualidade de Software.
    company: Radix Engenharia e Software.
    from: Março 2019
    to: Janeiro 2020
    description: >
      Development and administration of automated processes, API's to generate reports and business intelligence solutions. Services development based on cloud. Massive use of development based on cloud services, such as Amazon Web Services and Microsoft Azure.
    link: http://www.radixeng.com.br/
  item2:
    position:  Estagio em Data Science
    company: Mobi2Buy.
    from: Junho 2019
    to: Novembro 2019
    description: >
      Automação de Rotinas em Python e R , Criação de queries sql em Postgres/AWS.Redshift e Criação de rotinas com integração AWS.S3(Python/R).
    link: https://mobi2buy.com/


# Education section
education:
  item1:
    institution: Centro Universitário Carioca - Unicarioca/RJ
    program:  Bacharel em Ciência da Computação
    description: >
      Junto com a faculdade participei de alguns cursos: Como "Tecnicas Avançadas em programação" voltado para competição de programação.
    from: Fevereiro 2015
    to: Dezembro 2019
  item2:
    institution: Colegio Ludolf Reis
    program: Técnico em informática
    description: >
      Curso Voltado para Manutenção e Montagem de microcomputador
    from: Janeiro 2012
    to: Dezembro 2014

# Skills section
tools:
  # Consider that the following are icons:
  #   https://icons8.com/icons
  item1:
    img: c-sharp-logo-2
    title: C#
  item2:
    img: python
    title: Python
  item3:
    img: mysql-logo
    title: Mysql
  item6:
    img: linux
    title: Linux
  item7:
    img: c-plus-plus-logo
    title: C++
  item8:
    img: django
    title: Django
  item9:
    img: microsoft-sql-server
    title: Sql Server
  item10:
    img: java-coffee-cup-logo
    title: Java
  item11:
    img: amazon-web-services
    title: AWS Services
  item12:
    img: postgreesql
    title: Postgreesql
  item14:
    img: mongodb
    title: MongoDB
  item15:
    img: github
    title: Git
  item16:
    img: xbox-r
    title: Rscript

extra_skills:
  - Flask
  - Web scraping and web automation
  - Desenvolvimento de APIs
  - Testes Unitarios
  - Cloud Computing
  - Scripting
  - DevOps
  - Machine learning


# Talks and workshops section
workshops:
  item0:
    event: SCRUM FOUNDATION PROFESSIONAL CERTIFICATE (SFPC)
    workshop: ""
    material:
    link: https://www.docdroid.net/Qyb9fMy/certificate-rodrigo-cabral-pdf
  item1:
    event: O curso completo de Banco de Dados e SQL, sem mistérios!
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-T4IHAOR1/
  item2:
    event: "Python: Programação Orientada a Objetos com Python 3"
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-BVO7Y921/

# Projects section
projects:
  item1:
    title: flask resume template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    github: https://github.com/iamgilvan/flask-resume
    tags: [Flask, Python, Bootstrap]
  item3:
    title: TDD Python Example
    subtitle: Unit Test
    description: Unit test example development in python
    github: https://github.com/iamgilvan/tdd-python-example
    tags: [Python, Unit Test, PyTest]
  item4:
    title: Conversions of currencies
    subtitle: Conversions between different currencies
    description: The main objective of this API developed in Python, is to make conversions between different currencies with real and current quotes.
    github: https://github.com/iamgilvan/challenger-bravo
    tags: [Python, Flask, MongoDb, Heroku]
  item6:
    title: Airbnb Predict Price
    subtitle: Investigating Airbnb activity in Berlin, Germany
    description: ""
    github: https://gist.github.com/iamgilvan/73e2fc5864e4b3dd3c515028d114c488
    tags: [Python, Scikit-Learn, Matplotlib, Seaborn, Numpy, Pandas, Decision Tree Regressor]
  item7:
    title: Airbnb Predict Demands
    subtitle: Investigating Airbnb activity in Berlin, Germany
    description: ""
    github: https://gist.github.com/iamgilvan/06786c9ee39df937cbb04e895b0a5ab3
    tags: [Python, Matplotlib, Seaborn, Numpy, Pandas]
  item9:
    title: Natural language processing
    subtitle: Natural language processing exercice
    description: " "
    github: https://gist.github.com/iamgilvan/2c28d243922980f9c91113da12951388
    img: simple-omnitrix.png
    tags: [Python, Pandas, Scikit-Learn, Nltk]
