# Profile section
profile:
  first_name: Rodrigo
  last_name: Cabral
  picture: static/img/perfil.png # Local picture
  contact:
    address_one: São João de Meriti, Brasil
    address_two:
    phone: +55 21 99390-3683
  email: rodrigo.oliveiracabral@hotmail.com
  description: >
    Hello, welcome to my resume! I am a Bachelor of Computer Science, Unicarioca(2019.2). I am a Graduate Student in Data Science and BigData at PUC MINAS EAD. During 4 years of experience, I gained knowledge in Backend development, manual and automated tests. During this walk I used several programming languages such as: Python, NodeJS and also C#. I have intermediate knowledge in Database, having worked more with: Postgressql and MySql.

# Social section
social:
  github: https://github.com/RodrigoOBC
  linkedin: https://www.linkedin.com/in/rodrigo-cabral-0280b3121/


# Experience section
experience:
  item0:
    position: Software QA Pl
    company: Radix Engenharia e Software
    from: January 2022
    to: Present
    description: >
      Composition of "Test Cases";
      Composition of "Test Plans";
      Execution of "Test Script";
      Creation of "Test Cases" in BDDs;
      Automation of multi-language API cases;
      Automation of test cases written in BDD with Gauge;
      Automation with Selenium and Python or NodeJS;
      Automation with Cypress, Protractor, Playwright, and Puppeteer;
      Technical mentoring achievements.
    link: http://www.radixeng.com.br/
  item1:
    position: Software QA Jr
    company: Radix Engenharia e Software
    from: January 2020
    to: December 2021
    description: >
      Composition of "Test Cases";
      Composition of "Test Plans";
      Execution of "Test Script";
      Creation of "Test Cases" in BDDs;
      Automation of multi-language API cases;
      Automation of test cases written in BDD with Gauge;
      Automation with Selenium and Python or NodeJS;
      Automation with Cypress, Protractor, Playwright, and Puppeteer;
    link: http://www.radixeng.com.br/
  item2:
    position: Software QA Intern
    company: Radix Engenharia e Software.
    from: March 2019
    to: January 2020
    description: >
      Composition of "Test Cases" Composition of "Test Plans" ;
      Execution of "Test Script" ;
      Creation of "Test Cases" in BDDs ;
      Automation of multi-language API cases ;
      Automation of test cases written in BDD with Gauge;
    link: http://www.radixeng.com.br/
  item3:
    position: Data Science Intern
    company: Mobi2Buy.
    from: January 2018
    to: December 2018
    description: >
      Routine Automation in Python Routine Automation in R Creating sql queries in Postgres / AWS.Redshift Creating routines with integration AWS.S3 (Python / R)
    link: https://mobi2buy.com/


# Education section
education:
  item1:
    institution: Pontifícia Universidade Católica de Minas Gerais - PUC MINAS EAD
    program: Postgraduate in Data Science and BigData
    description:
    from: August 2020
    to: March 2022
  item2:
    institution: YES! Idiomas
    program: Curso de inglês
    description: >
      5° Semestre
    from: January 2020
    to: No end date
  item3:
    institution: Centro Universitário Carioca - Unicarioca/RJ
    program: Bachelor in Computer Science
    description: >
    from: February 2015
    to: December 2019
  item4:
    institution: Colegio Ludolf Reis
    program: Computer Technician
    description: >
    from: January 2012
    to: December 2014

# Skills section
tools:
  # Consider that the following are icons:
  #   https://icons8.com/icons
  item1:
    img: c-sharp-logo-2
    title: C#
  item2:
    img: python
    title: Python
  item3:
    img: nodejs
    title: Nodejs
  item4:
    img: tensorflow
    title: Tensorflow
  item5:
    img: mysql-logo
    title: Mysql
  item6:
    img: linux
    title: Linux
  item7:
    img: c-plus-plus-logo
    title: C++
  item8:
    img: django
    title: Django
  item9:
    img: microsoft-sql-server
    title: Sql Server
  item10:
    img: java-coffee-cup-logo
    title: Java
  item11:
    img: amazon-web-services
    title: AWS Services
  item12:
    img: postgreesql
    title: Postgreesql
  item14:
    img: mongodb
    title: MongoDB
  item15:
    img: github
    title: Git
  item16:
    img: xbox-r
    title: Rscript
  item17:
    img: selenium
    title: Selenium


extra_skills:
  - Flask
  - Web scraping and web automation
  - Desenvolvimento de APIs
  - Testes Unitarios
  - Cloud Computing
  - Scripting
  - DevOps
  - Machine learning
  - Neural Networking(RNA ou CNN)
  - k6
  - Playwright


Curriculo:
  item0:
    link: static/Curriculo/Curriculo_Rodrigo_Cabral.pdf
    picture: static/img/pdf.png

Artigos:
  item0:
    link: https://medium.com/@rodrigo.oliveiracabral/playwright-cucumber-com-page-object-4c4b8d67a8c
    name: Playwright + Cucumber com Page Object
  item1:
    link: https://medium.com/@rodrigo.oliveiracabral/teste-de-integra%C3%A7%C3%A3o-com-k6-10a5f3912e75
    name: Teste de Integração com k6
  item2:
    link: https://doi.org/10.29327/4467215
    name: Trabalho de Conclusão de Curso da Pós-Graduação em Ciência de Dados e Big Data
# Talks and workshops section
workshops:
  item0:
    event: SCRUM FOUNDATION PROFESSIONAL CERTIFICATE (SFPC)
    workshop: ""
    material:
    link: https://www.docdroid.net/Qyb9fMy/certificate-rodrigo-cabral-pdf
  item1:
    event: O curso completo de Banco de Dados e SQL, sem mistérios!
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-T4IHAOR1/
  item2:
    event: "Python: Programação Orientada a Objetos com Python 3"
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-BVO7Y921/
  item3:
    event: "Linguagem de Programação C# - Básico"
    workshop: ""
    material:
    link: https://i.ibb.co/JdmjTrj/Certificado-Bradesco-Csharp.jpg
  item4:
    event: "IMPLEMENTANDO BANCOS DE DADOS"
    workshop: ""
    material:
    link: https://ibb.co/1vB67fQ
  item5:
    event: "The Complete Python 3 Course: Go from Beginner to Advanced!"
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-UOPDZORR/

# Projects section
projects:
  item1:
    title: Currículo Lattes
    subtitle: Currículo Lattes feito em flask
    description: ""
    github: https://github.com/RodrigoOBC/flask-resume/tree/Rodrigo_Cabral
    tags: [ Flask, Python, Bootstrap ]
  item2:
    title: Notebooks Redes Neurais
    subtitle: Notebooks com Redes Neurais Artificiais
    description: "Uma serie de Notebooks com Redes neurais"
    github: https://github.com/RodrigoOBC/Notebooks_RedesNeurais
    tags: [ Python, jupyter, TensorFlow ]
  item3:
    title: Servidor de chat
    subtitle: Servidor de chat em Python
    description: Um siples sistema que simula um "servidor de chat", com a visão cliente e servidor
    github: https://github.com/RodrigoOBC/chat_servidor
    tags: [ Python ]
  item4:
    title: Test de integração de API com K6
    subtitle: Test de integração de API com K6
    description: ""
    github: https://github.com/RodrigoOBC/Test-API-K6
    tags: [ Nodejs, K6 ]
  item5:
    title: Framework Playwright com Python-BDD
    subtitle: Framework Playwright com Python-BDD
    description: "Para o projeto foram utilizados as linguagem Python na sua versão 3.8 (compativel da 3.7 ou +), Playwright 1.10.0 e também o Behave para escrita dos BDDs."
    github: https://github.com/RodrigoOBC/playwright_Behave_python
    tags: [ Playwright, Python, Behave ]
  item6:
    title: Framework Playwright com Cucumber
    subtitle: Framework Playwright com Cucumber
    description: ""
    github: https://github.com/RodrigoOBC/PlaywrightFrameworkCucumber
    tags: [ Nodejs, Playwright, Cucumber ]
  item7:
    title: Framework Ruby com Capybara-BDD
    subtitle: Framework Ruby com Capybara-BDD
    description: ""
    github: https://github.com/RodrigoOBC/Ruby_BDD_Capybara
    tags: [ Ruby, Capybara ]
  item8:
    title: FrameWork Selenium Python-BDD
    subtitle: FrameWork Selenium Python-BDD
    description: ""
    github: https://github.com/RodrigoOBC/FrameWorkSeleniumPythonBDD
    tags: [ Python, Selenium ]
  item9:
      title: Desafio Livelo
      subtitle: Desafio Livelo
      description: ""
      github: https://github.com/RodrigoOBC/desafio_livelo
      tags: [ Python, Selenium, Behave, BDD ]