# Profile section
profile:
  first_name: Rodrigo
  last_name: Cabral
  picture: static/img/perfil.png # Local picture
  contact:
    address_one: São João de Meriti, Brasil
    address_two:
    phone: +55 21 99390-3683
  email: rodrigo.oliveiracabral@hotmail.com
  description: >
    Olá, bem-vindo ao meu currículo! Sou Bacharel em Ciência da Computação, Unicarioca(2019.2). Sou apaixonado por novas tecnologias. Tenho 2 anos de experiência, tenho conhecimento médio em programação backend, conhecimento avançado em banco de dados relacionais, como por exemplo "Postgres, mysql, sqlServer entre outros".Tenho conhecimento em IA, tema esse do meu TCC.

# Social section
social:
  github: https://github.com/RodrigoOBC
  linkedin: https://www.linkedin.com/in/rodrigo-cabral-0280b3121/


# Experience section
experience:
  item0:
    position: Analista de Teste de Software Jr.
    company: Radix Engenharia e Software
    from: Janeiro 2020
    to: Present
    description: Composição de "Casos de Teste", Composição de "Planos de Teste", Execução de "Roteiro de Teste", Criação de "Casos de Teste" em BDDs, Automatização dos casos de API. Multiplas linguagens, Automatização dos casos de teste, escritos em BDD com Gauge
    link: http://www.radixeng.com.br/
  item1:
    position: Estagiario de Teste e Qualidade de Software.
    company: Radix Engenharia e Software.
    from: Março 2019
    to: Janeiro 2020
    description: >
      Composição de "Casos de Teste", Composição de "Planos de Teste", Execução de "Roteiro de Teste", Criação de "Casos de Teste" em BDDs, Automatização dos casos de API. Multiplas linguagens, Automatização dos casos de teste, escritos em BDD com Gauge
    link: http://www.radixeng.com.br/
  item2:
    position:  Estagio em Data Science
    company: Mobi2Buy.
    from: Janeiro 2018
    to: Dezembro 2018
    description: >
      Automação de Rotinas em Python e R , Criação de queries sql em Postgres/AWS.Redshift e Criação de rotinas com integração AWS.S3(Python/R).
    link: https://mobi2buy.com/


# Education section
education:
  item1:
    institution: Pontifícia Universidade Católica de Minas Gerais - PUC MINAS EAD
    program: Pós-Graduação em Ciência de Dados e BigData
    description: >
      Pós-Graduação em Ciência de Dados e BigData, areá que mais cresce no mercado (Nacional/internacional).
    from: Agosto 2020
    to: Dezembro 2021
  item2:
    institution: YES! Idiomas
    program: Curso de inglês
    description: >
    from: Janeiro 2020
    to: Ainda sem data final
  item3:
    institution: Centro Universitário Carioca - Unicarioca/RJ
    program:  Bacharel em Ciência da Computação
    description: >
      Junto com a faculdade participei de alguns cursos: Como "Tecnicas Avançadas em programação" voltado para competição de programação.
    from: Fevereiro 2015
    to: Dezembro 2019
  item4:
    institution: Colegio Ludolf Reis
    program: Técnico em informática
    description: >
      Curso Voltado para Manutenção e Montagem de microcomputador
    from: Janeiro 2012
    to: Dezembro 2014

# Skills section
tools:
  # Consider that the following are icons:
  #   https://icons8.com/icons
  item1:
    img: c-sharp-logo-2
    title: C#
  item2:
    img: python
    title: Python
  item3:
    img: mysql-logo
    title: Mysql
  item6:
    img: linux
    title: Linux
  item7:
    img: c-plus-plus-logo
    title: C++
  item8:
    img: django
    title: Django
  item9:
    img: microsoft-sql-server
    title: Sql Server
  item10:
    img: java-coffee-cup-logo
    title: Java
  item11:
    img: amazon-web-services
    title: AWS Services
  item12:
    img: postgreesql
    title: Postgreesql
  item14:
    img: mongodb
    title: MongoDB
  item15:
    img: github
    title: Git
  item16:
    img: xbox-r
    title: Rscript

extra_skills:
  - Flask
  - Web scraping and web automation
  - Desenvolvimento de APIs
  - Testes Unitarios
  - Cloud Computing
  - Scripting
  - DevOps
  - Machine learning


Curriculo:
  item0:
    link: static/Curriculo/Curriculo2020.pdf
    picture: static/img/pdf.png

# Talks and workshops section
workshops:
  item0:
    event: SCRUM FOUNDATION PROFESSIONAL CERTIFICATE (SFPC)
    workshop: ""
    material:
    link: https://www.docdroid.net/Qyb9fMy/certificate-rodrigo-cabral-pdf
  item1:
    event: O curso completo de Banco de Dados e SQL, sem mistérios!
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-T4IHAOR1/
  item2:
    event: "Python: Programação Orientada a Objetos com Python 3"
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-BVO7Y921/
  item3:
    event: "Linguagem de Programação C# - Básico"
    workshop: ""
    material:
    link: https://i.ibb.co/JdmjTrj/Certificado-Bradesco-Csharp.jpg
  item4:
    event: "IMPLEMENTANDO BANCOS DE DADOS"
    workshop: ""
    material:
    link: https://ibb.co/1vB67fQ
  item5:
    event: "The Complete Python 3 Course: Go from Beginner to Advanced!"
    workshop: ""
    material:
    link: https://www.udemy.com/certificate/UC-UOPDZORR/

# Projects section
projects:
  item1:
    title: flask resume template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    github: https://github.com/RodrigoOBC/flask-resume/tree/Rodrigo_Cabral
    tags: [Flask, Python, Bootstrap]
  item2:
    title: Programas-Simples
    subtitle: Programas feitos em python
    description: ""
    github: https://github.com/RodrigoOBC/Programas-Simples
    tags: [Python]
  item3:
    title: Servidor de chat
    subtitle: Servidor de chat em Python
    description: Um siples sistema que simula um "servidor de chat", com a visão cliente e servidor
    github: https://github.com/RodrigoOBC/chat_servidor
    tags: [Python]
  item4:
    title: API Star Wars Nodejs
    subtitle: Desafio API Star Wars
    description: ""
    github: https://github.com/RodrigoOBC/API_star_wars_nodjs
    tags: [ Nodejs, MongoDB ]

  item5:
    title: INTELIGÊNCIA ARTIFICIAL APLICADA NA ANÁLISE DE RISCO PARA SEGUROS DE VIDA
    subtitle: TCC Ciência da Computação
    description: ""
    github: https://github.com/RodrigoOBC/Teclado-Virtual-Atualizado-APS
    tags: [Flask, Python, Bootstrap]

  item6:
    title: Desafio B2w
    subtitle: Desafio Star Wars
    description: ""
    github: https://github.com/RodrigoOBC/desafio_b2w
    tags: [Flask, Python, Postman]


